support plexpass builds via token

diff --git a/plex-upgrade b/plex-upgrade
--- a/plex-upgrade
+++ b/plex-upgrade
@@ -7,6 +7,7 @@
 # License: MIT
 
 pkgdir=~/.plex/pkg
+plexurl='https://plex.tv/downloads'
 
 fatal() {
 	echo "FATAL: $*" >&2
@@ -20,7 +21,8 @@ read -r _ installed < <(dpkg-query -W plexmediaserver 2>/dev/null)
 echo "installed: ${installed:-(none)}"
 
 # grab the packages
-html=$(curl -sS https://plex.tv/downloads) || fatal 'failed to list packages'
+[[ -n $1 ]] && plexurl="https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token=$1"
+html=$(curl -sS $plexurl) || fatal 'failed to list packages'
 
 # find the latest deb
 read -r version url < <(perl -lne '/<a href="([^"]+\/plexmediaserver_([^ ]+)_amd64\.deb)"/ && printf "$2 $1\n"' <<< "$html")
